### PR TITLE
Add code coverage with Codecov

### LINKED ISSUE #165: Add Code Coverage
Would be nice to generate a codecoverage number like libraries such as https://github.com/alteryx/featuretools

image

Should to add to both readme and github actions that run on every PR

### PR DESCRIPTION
**Pull request by gsheni**
- Fixes #165

### CODE REVIEW

**Comment by gsheni** [comment]
@kmax12 ready for review. It should work once the repo is setup on Codecov

**Comment by kmax12** [comment]
i added the codecov secret to the repo, but the 3.11 tests arent even reaching the point at which it runs. any idea what might be going on? going to try to rerun

**Comment by gsheni** [comment]
@kmax12 fixed it. 
I forgot to add the slow/re-run args to `make test-cov` command (leading the CI to run the slow unit tests).

**Comment by gsheni** [comment]
The tests failed but I've seen this before. They failed towards the end of day ET (because the data is not available to query for the new day?).

**Comment by kmax12** [comment]
looking good. the only issue seems to be with codecov token now. i suspect it has to do with the being a fork so the secret token isn't available. going to merge in and see if it resolves itself. 

thanks again for the contribution!

**Comment by gsheni** [comment]
Codecov isn't working on `main` is because the unit tests are **not run on** merge to `main`. The `tests.yaml` workflow needs to be updated.
Does it matter if all Python unit tests are run on main? Do you only want to run unit tests for Python 3.11 on merge to `main`?

**Comment by kmax12** [comment]
Ah, let's just do 3.11 on main

**Pull request merged**
