### PR TITLE
NYISO AS Prices

### PR DESCRIPTION
**Pull request by kmax12**

### CODE REVIEW

**Comment by jcsalterego** [comment]
This branch is for illustrative purposes :)

**Comment by kmax12** [comment]
ya, sorry. my local workflow for checkouting branches from forked repos requires a PR. 

when I run ` pytest gridstatus/tests/test_nyiso.py -k 'get_as_prices'  ` I get different errors. the first looks like [202202 folder missing data](http://mis.nyiso.com/public/csv/rtasp/20220201rtasp_csv.zip). and the second seems to be nyiso site missing data for today. 

I wonder why were seeing different things. I'm running this on python 3.10

<details>
<summary>Failed Test 1</summary>

```python
    def test_get_as_prices4(self):
        as_cols = [
            "Time",
            "Region Market",
            "10 Min Spinning Reserve",
            "10 Min Non-Synchronous Reserve",
            "30 Min Operating Reserve",
            "Regulation Capacity",
            "Regulation Movement",
        ]
        today = pd.Timestamp.now(tz=self.iso.default_timezone).date()
        date = today - pd.DateOffset(days=365)
>       df = self.iso.get_as_prices(date)

gridstatus/tests/test_nyiso.py:75: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
gridstatus/decorators.py:78: in wrapped_f
    df = f(**args_dict)
gridstatus/nyiso.py:591: in get_as_prices
    df = self._download_nyiso_archive(
gridstatus/nyiso.py:705: in _download_nyiso_archive
    df = pd.read_csv(z.open(csv_filename))
../../.pyenv/versions/3.10.2/lib/python3.10/zipfile.py:1503: in open
    zinfo = self.getinfo(name)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <zipfile.ZipFile file=<_io.BytesIO object at 0x12857e3e0> mode='r'>, name = '20220218rtasp.csv'

    def getinfo(self, name):
        """Return the instance of ZipInfo given 'name'."""
        info = self.NameToInfo.get(name)
        if info is None:
>           raise KeyError(
                'There is no item named %r in the archive' % name)
E           KeyError: "There is no item named '20220218rtasp.csv' in the archive"
```
</details>

and 

<details>
<summary>Failed Test 2</summary>

```python
self = <gridstatus.tests.test_nyiso.TestNYISO object at 0x11fdd7f10>

    def test_get_as_prices3(self):
        as_cols = [
            "Time",
            "Region Market",
            "10 Min Spinning Reserve",
            "10 Min Non-Synchronous Reserve",
            "30 Min Operating Reserve",
            "Regulation Capacity",
            "Regulation Movement",
        ]
        today = pd.Timestamp.now(tz=self.iso.default_timezone).date()
        date = pd.Timestamp(2022, 11, 8).date()
>       df = self.iso.get_as_prices(date, end="today")

gridstatus/tests/test_nyiso.py:57: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
gridstatus/decorators.py:206: in wrapped_f
    df = pd.concat(all_df).reset_index(drop=True)
../../.pyenv/versions/3.10.2/envs/isodata/lib/python3.10/site-packages/pandas/util/_decorators.py:311: in wrapper
    return func(*args, **kwargs)
../../.pyenv/versions/3.10.2/envs/isodata/lib/python3.10/site-packages/pandas/core/reshape/concat.py:347: in concat
    op = _Concatenator(
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <pandas.core.reshape.concat._Concatenator object at 0x1283d6110>, objs = [], axis = 0, join = 'outer'
keys = None, levels = None, names = None, ignore_index = False, verify_integrity = False, copy = True
sort = False

    def __init__(
        self,
        objs: Iterable[NDFrame] | Mapping[Hashable, NDFrame],
        axis=0,
        join: str = "outer",
        keys=None,
        levels=None,
        names=None,
        ignore_index: bool = False,
        verify_integrity: bool = False,
        copy: bool = True,
        sort=False,
    ):
        if isinstance(objs, (ABCSeries, ABCDataFrame, str)):
            raise TypeError(
                "first argument must be an iterable of pandas "
                f'objects, you passed an object of type "{type(objs).__name__}"'
            )
    
        if join == "outer":
            self.intersect = False
        elif join == "inner":
            self.intersect = True
        else:  # pragma: no cover
            raise ValueError(
                "Only can inner (intersect) or outer (union) join the other axis"
            )
    
        if isinstance(objs, abc.Mapping):
            if keys is None:
                keys = list(objs.keys())
            objs = [objs[k] for k in keys]
        else:
            objs = list(objs)
    
        if len(objs) == 0:
>           raise ValueError("No objects to concatenate")
E           ValueError: No objects to concatenate
```
</details>

**Comment by WillKoehrsen** [comment]
Do we still want to get this merged? Or is this superseded by #274?

**Comment by kmax12** [comment]
this is a dataset we're still interested in, but we should recreate a PR to do it. there maybe some tests we can take from this one to speed things up. Closing this and added new issue: #333

**Pull request closed without merging**
